// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace E_Commerce.DAL.Models;

[Table("Category")]
public partial class Category
{
    [Key]
    public int CatId { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string CatName { get; set; }

    [Required]
    [Unicode(false)]
    public string CatImage { get; set; }

    public bool IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDate { get; set; }


    [JsonIgnore]
    [InverseProperty("Cat")]
    public virtual ICollection<Product> Products { get; set; } = new List<Product>();


    [InverseProperty("Category")]
    public virtual ICollection<SubCategory> SubCategories { get; set; } = new List<SubCategory>();
}