// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace E_Commerce.DAL.Models;

[Table("Contact")]
public partial class Contact
{
    [Key]
    public int ContactId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Subject { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Message { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDate { get; set; }
}