// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace E_Commerce.DAL.Models;

[Table("Payment")]
public partial class Payment
{
    [Key]
    public int PaymentId { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    public int? CardNo { get; set; }

    [StringLength(50)]
    public string ExpDate { get; set; }

    [StringLength(50)]
    public string CVVNo { get; set; }

    [StringLength(50)]
    public string Address { get; set; }

    [StringLength(50)]
    public string PaymentMode { get; set; }

    [InverseProperty("Payment")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}