// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace E_Commerce.DAL.Models;

[Table("ProductReview")]
public partial class ProductReview
{
    [Key]
    public int ReviewId { get; set; }

    public int Rating { get; set; }

    [Unicode(false)]
    public string Comment { get; set; }

    public int ProductId { get; set; }

    public int UserId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDate { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("ProductReviews")]
    public virtual Product Product { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("ProductReviews")]
    public virtual User User { get; set; }
}