// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace E_Commerce.DAL.Models;

[Table("ProductImage")]
public partial class ProductImage
{
    [Key]
    public int ImageId { get; set; }

    [Unicode(false)]
    public string ImageUrl { get; set; }

    public int ProductId { get; set; }

    public bool? DefaultImg { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("ProductImages")]
    public virtual Product Product { get; set; }
}